import "./globals.css";
import type { Metadata } from "next";
import { Baskervville, Montserrat } from "next/font/google";

const basker = Baskervville({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-basker",
});
const mont = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${basker.variable} ${mont.variable}`}>{children}</body>
    </html>
  );
}
